name: CI

on:
  push:
  schedule:
  - cron: '15 7 * * 3'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.17'

    - uses: actions/checkout@v2

    - name: Install deps
      run: make deps

    - name: Build
      run: make build

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./build/*
        tag: ${{ github.ref_name }}
        overwrite: true
        file_glob: true
